
export enum LiveInsightAnomalyReportType {
  INTERFACE_UTILIZATION = 'INTERFACE_UTILIZATION',
  APPLICATION_UTILIZATION = 'APPLICATION_UTILIZATION',
  APPLICATION_PERFORMANCE = 'APPLICATION_PERFORMANCE',
  SNMP_CLASS_BANDWIDTH_ANOMALIES = 'SNMP_CLASS_BANDWIDTH_ANOMALIES',
  UNKNOWN = 'UNKNOWN',
}
