export const ChipColors = [
  {chip: '#C3DFF3', group: '#DCEDFA'},
  {chip: '#C4E1EA', group: '#DFEFF5'},
  {chip: '#C4EBE7', group: '#DCF5F3'},
  {chip: '#D5D7EE', group: '#E6E6F7'},
  {chip: '#E2D1EB', group: '#F1E6F7'},
  {chip: '#F5C8DB', group: '#FAE3ED'},
  {chip: '#F8DBD8', group: '#FCEAE8'},
  {chip: '#FDE2CE', group: '#FCEFE6'},
  {chip: '#D6DDE0', group: '#E4EDF0'},
  {chip: '#C4E0EF', group: '#E1F0FA'},
  {chip: '#D0F1D2', group: '#E6FAE8'},
  {chip: '#FAEBD1', group: '#FCF3E6'},
  {chip: '#FBDFDF', group: '#FCEBEB'},
  {chip: '#FAF3D6', group: '#FCF8E9'},
  {chip: '#E1FAD6', group: '#EFFCE9'},
  {chip: '#F8E2F8', group: '#FBEFFB'},
  {chip: '#FAFAC7', group: '#FBFBDF'},
  {chip: '#E2DFDF', group: '#F0EFEF'},
  {chip: '#E0DEED', group: '#F0EFF6'},
  {chip: '#EDE6D9', group: '#F7F4EE'},
  {chip: '#D1EACD', group: '#EBF6EA'},
  {chip: '#DFE6D1', group: '#F1F4EB'},
  {chip: '#E6D6E6', group: '#F3ECF3'}
];
