export class FilterFixtures {
  static readonly filterTags = {
    site: [
      'Berlin',
      'Bla(ck)&hole|=asdasd',
      'Black Hole',
      'Branch1',
      'Branch2',
      'Brazil',
      'Brown',
      'Chicago',
      'China',
      'Constelation',
      'Constellation',
      'Daisy',
      'Dandelion',
      'Datacenter',
      'Dead Sea',
      'Dubai',
      'England',
      'France',
      'Galaxy',
      'HUB',
      'Hawaii',
      'India',
      'Japan',
      'London',
      'LondonEdge',
      'Los Angel',
      'Los Vegas',
      'Mars',
      'Melbourne',
      'Miami',
      'Milky Way',
      'Montreal',
      'NewYorkEdge',
      'PaloAlto',
      'Phoenix',
      'Pink',
      '<<Site>>',
    ],
    device: [
      'C3850-A-14',
      'C3850-A-15',
      'HUB2_234.liveaction.com',
      'HUB_232.liveaction.com',
      'ISR-4331-A-19.liveaction.com',
      'LDN-SwitchV1.liveaction.com',
      'LondonEdge',
      'MC1_229.liveaction.com',
      'MIAMI-VE-02',
      'MONTREAL-VE-04',
      'MPLS-INET-CLOUD.liveaction.com',
      'NYC-SwitchV2.liveaction.com',
      'NetScaler',
      'PA-CSR-01.liveaction.com',
      'PA-CSR-02.liveaction.com',
      'PHOENIX-VE-05',
      'PHOENIX-VE-06',
      'PaloAlto-VE-01',
      'SPOKE2_248.liveaction.com',
      'SPOKE_247.liveaction.com',
      'TXS-SwitchV2.liveaction.com',
      'TexasEdge',
      'VANCOUVER-VE-03',
      'vBond1',
      'vManage1',
      'vSmart1',
    ],
    interfaceAndDevice: [
      {
        device: {
          deviceSerial: '10.1.40.33:1586170016627',
          deviceHostName: 'livewire',
          deviceSystemName: 'livewire',
        },
        interfaces: ['lo', 'eth3', 'eth2', 'eth4', 'MGMT'],
      },
      {
        device: {
          deviceSerial: '96U6N2R58B5',
          deviceHostName: 'LDN-SwitchV1',
          deviceSystemName: 'LDN-SwitchV1.liveaction.com',
        },
        interfaces: [
          'Null0',
          'VoIP-Null0',
          'GigabitEthernet1',
          'GigabitEthernet2',
          'GigabitEthernet3',
        ],
      },
      {
        device: {
          deviceSerial: '83F88D47',
          deviceHostName: 'LondonEdge',
          deviceSystemName: 'LondonEdge',
        },
        interfaces: [
          'ge0/0',
          'ge0/1',
          'ge0/2',
          'ge0/3',
          'ge0/4',
          'ge0/5',
          'system',
          'ge0/7',
        ],
      },
      {
        device: {
          deviceSerial: '9GE9ONU3NJ1',
          deviceHostName: 'MPLS-INET-CLOUD',
          deviceSystemName: 'MPLS-INET-CLOUD.liveaction.com',
        },
        interfaces: [],
      },
      {
        device: {
          deviceSerial: '63674414',
          deviceHostName: 'PaloAlto-VE-01',
          deviceSystemName: 'PaloAlto-VE-01',
        },
        interfaces: [
          'ge0/0',
          'ge0/1',
          'system',
          'vmanage_system',
          'ge0/2.101',
          'ge0/2.102',
          'eth0',
        ],
      },
      {
        device: {
          deviceSerial: 'HE2H81UJ47',
          deviceHostName: 'NetScaler',
          deviceSystemName: 'NetScaler',
        },
        interfaces: ['LO/1', '0/1'],
      },
      {
        device: {
          deviceSerial: '20E00EB0',
          deviceHostName: 'MONTREAL-VE-04',
          deviceSystemName: 'MONTREAL-VE-04',
        },
        interfaces: [
          'ge0/0',
          'ge0/1',
          'ge0/3',
          'system',
          'vmanage_system',
          'ge0/2.401',
          'ge0/2.402',
          'ge0/2.403',
          'eth0',
        ],
      },
      {
        device: {
          deviceSerial: '9FH785H2P28',
          deviceHostName: 'HUB_232',
          deviceSystemName: 'HUB_232.liveaction.com',
        },
        interfaces: [
          'Null0',
          'Tunnel10',
          'GigabitEthernet1',
          'GigabitEthernet2',
          'GigabitEthernet3',
          'GigabitEthernet4',
        ],
      },
      {
        device: {
          deviceSerial: '9H4C98RFILR',
          deviceHostName: 'MC1_229',
          deviceSystemName: 'MC1_229.liveaction.com',
        },
        interfaces: [
          'GigabitEthernet1',
          'GigabitEthernet2',
          'GigabitEthernet5',
          'GigabitEthernet4',
        ],
      },
      {
        device: {
          deviceSerial: '9RA047IBN39',
          deviceHostName: 'HUB2_234',
          deviceSystemName: 'HUB2_234.liveaction.com',
        },
        interfaces: [
          'Loopback47233',
          'Tunnel11',
          'Tunnel47233',
          'GigabitEthernet1',
          'GigabitEthernet4',
        ],
      },
      {
        device: {
          deviceSerial: '9B68IV2ARHE',
          deviceHostName: 'PA-CSR-01',
          deviceSystemName: 'PA-CSR-01.liveaction.com',
        },
        interfaces: [
          'Loopback100',
          'Null0',
          'VoIP-Null0',
          'GigabitEthernet2',
          'GigabitEthernet3',
          'GigabitEthernet4',
        ],
      },
      {
        device: {
          deviceSerial: '9BDODFOYV8P',
          deviceHostName: 'PA-CSR-02',
          deviceSystemName: 'PA-CSR-02.liveaction.com',
        },
        interfaces: [
          'Loopback100',
          'Null0',
          'Tunnel200',
          'Tunnel0',
          'VoIP-Null0',
          'GigabitEthernet2',
          'GigabitEthernet3',
        ],
      },
      {
        device: {
          deviceSerial: '9U9EQD5NCES',
          deviceHostName: 'SPOKE_247',
          deviceSystemName: 'SPOKE_247.liveaction.com',
        },
        interfaces: ['Tunnel10', 'GigabitEthernet1', 'GigabitEthernet2'],
      },
      {
        device: {
          deviceSerial: '9IZTDXZLD6A',
          deviceHostName: 'PA-CSR-03',
          deviceSystemName: 'PA-CSR-03.liveaction.com',
        },
        interfaces: [],
      },
      {
        device: {
          deviceSerial: '9IRVE649AQF',
          deviceHostName: 'PA-CSR-04',
          deviceSystemName: 'PA-CSR-04.liveaction.com',
        },
        interfaces: [],
      },
      {
        device: {
          deviceSerial: '9JTNT7K30UN',
          deviceHostName: 'SPOKE2_248',
          deviceSystemName: 'SPOKE2_248.liveaction.com',
        },
        interfaces: ['GigabitEthernet1', 'GigabitEthernet3'],
      },
      {
        device: {
          deviceSerial: '9CJ9ZOCTKL0',
          deviceHostName: 'NYC-SwitchV2',
          deviceSystemName: 'NYC-SwitchV2.liveaction.com',
        },
        interfaces: [
          'Null0',
          'VoIP-Null0',
          'GigabitEthernet1',
          'GigabitEthernet2',
          'GigabitEthernet3',
        ],
      },
      {
        device: {
          deviceSerial: '9BWML6BEMR9',
          deviceHostName: 'TXS-SwitchV2',
          deviceSystemName: 'TXS-SwitchV2.liveaction.com',
        },
        interfaces: [
          'Null0',
          'VoIP-Null0',
          'GigabitEthernet1',
          'GigabitEthernet2',
          'GigabitEthernet3',
          'GigabitEthernet4',
        ],
      },
      {
        device: {
          deviceSerial: '9608UCQXQMU',
          deviceHostName: 'NYC-SwitchV1',
          deviceSystemName: 'NYC-SwitchV1.liveaction.com',
        },
        interfaces: [],
      },
      {
        device: {
          deviceSerial: 'FLM2015W0RV',
          deviceHostName: 'ISR-4331-A-19',
          deviceSystemName: 'ISR-4331-A-19.liveaction.com',
        },
        interfaces: [],
      },
      {
        device: {
          deviceSerial: '9AE63JRIAN8',
          deviceHostName: 'PA-CSR-05-ISP',
          deviceSystemName: 'PA-CSR-05-ISP.liveaction.com',
        },
        interfaces: [],
      },
    ],
  };
}
